# Generated by Django 5.2.16 on 2026-07-12 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_default_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="实际余额"
                    ),
                ),
                (
                    "calculated_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="核对前系统余额"
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="差额"
                    ),
                ),
                ("checked_at", models.DateTimeField(verbose_name="核对时间")),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "adjustment_transaction_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="余额调整交易 ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="accounts.account",
                        verbose_name="账户",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["account", "checked_at"],
                        name="accounts_ac_account_a4daef_idx",
                    )
                ],
            },
        ),
    ]
