# Generated by Django 5.2.17 on 2026-08-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountreconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('BANK', '银行卡'), ('WECHAT', '微信余额'), ('ALIPAY', '支付宝余额'), ('CREDIT_CARD', '信用卡'), ('WEALTH', '理财账户')], max_length=20, verbose_name='账户类型'),
        ),
    ]
