# Generated by Django 5.2.16 on 2026-07-13 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systempreference",
            name="login_failure_global_limit",
            field=models.PositiveSmallIntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="systempreference",
            name="login_failure_ip_limit",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="systempreference",
            name="login_failure_window_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1440),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="systempreference",
            name="session_absolute_timeout_hours",
            field=models.PositiveSmallIntegerField(
                default=24,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8760),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="systempreference",
            name="session_idle_timeout_minutes",
            field=models.PositiveSmallIntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10080),
                ],
            ),
        ),
    ]
