# Generated by Django 5.2.16 on 2026-07-13 08:27

from django.db import migrations, models


def create_maintenance_state(apps, schema_editor):
    apps.get_model("core", "MaintenanceState").objects.get_or_create(pk=1, defaults={"enabled": False})


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_systempreference_login_failure_global_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("USER_EXPORT", "用户业务备份"),
                            ("PRE_RESTORE", "恢复前自动备份"),
                            ("RESTORE", "用户业务恢复"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "执行中"),
                            ("SUCCEEDED", "成功"),
                            ("FAILED", "失败"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("app_version", models.CharField(max_length=30)),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("error_summary", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="core_single_maintenance_state",
                    )
                ],
            },
        ),
        migrations.RunPython(create_maintenance_state, migrations.RunPython.noop),
    ]
