# Generated by Django 5.2.16 on 2026-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_backuprun_maintenancestate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuprun",
            name="backup_type",
            field=models.CharField(
                choices=[
                    ("USER_EXPORT", "用户业务备份"),
                    ("PRE_RESTORE", "恢复前自动备份"),
                    ("RESTORE", "用户业务恢复"),
                    ("DB_DAILY", "每日数据库备份"),
                    ("DB_WEEKLY", "每周数据库备份"),
                    ("DB_DEPLOYMENT", "部署前数据库备份"),
                    ("DB_MANUAL", "手工数据库备份"),
                    ("DB_RESTORE", "数据库恢复"),
                ],
                max_length=20,
            ),
        ),
    ]
