# Generated by Django 5.2.16 on 2026-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_backuprun_backup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempreference',
            name='active_theme_id',
            field=models.CharField(default='safe-default', max_length=80),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='appearance_mode',
            field=models.CharField(choices=[('AUTO', '跟随主题'), ('LIGHT', '浅色'), ('DARK', '深色')], default='AUTO', max_length=8),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='last_known_good_theme_id',
            field=models.CharField(default='safe-default', max_length=80),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='show_theme_background',
            field=models.BooleanField(default=True),
        ),
    ]
