# Generated by Django 5.2.16 on 2026-07-12 14:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "category_type",
                    models.CharField(
                        choices=[("INCOME", "收入"), ("EXPENSE", "支出")],
                        max_length=10,
                        verbose_name="分类类型",
                    ),
                ),
                (
                    "necessity",
                    models.CharField(
                        blank=True,
                        choices=[("NECESSARY", "必要消费"), ("FLEXIBLE", "弹性消费")],
                        max_length=10,
                        null=True,
                        verbose_name="消费性质",
                    ),
                ),
                (
                    "default_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="默认预算",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="显示顺序"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category_type", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["category_type", "is_active", "sort_order"],
                        name="ledger_cate_categor_e52c10_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category_type", "name"),
                        name="ledger_unique_category_name_per_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("default_budget__gte", Decimal("0.00"))),
                        name="ledger_default_budget_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("category_type", "EXPENSE"),
                                ("necessity__isnull", False),
                            ),
                            models.Q(
                                ("category_type", "INCOME"), ("necessity__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="ledger_category_necessity_matches_type",
                    ),
                ],
            },
        ),
    ]
