# Generated by Django 5.2.16 on 2026-07-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_default_accounts"),
        ("ledger", "0002_default_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商家名称")),
                (
                    "normalized_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="标准化名称"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "收入"),
                            ("EXPENSE", "支出"),
                            ("TRANSFER", "转账"),
                            ("REFUND", "退款"),
                            ("BALANCE_ADJUSTMENT", "余额调整"),
                        ],
                        max_length=24,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "有效"),
                            ("VOID", "作废"),
                            ("REVERSED", "已反向修正"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="金额"
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="发生时间")),
                (
                    "budget_month",
                    models.DateField(blank=True, null=True, verbose_name="预算月份"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("BANK", "银行"),
                            ("WECHAT", "微信"),
                            ("ALIPAY", "支付宝"),
                            ("DIRECT", "直接交易"),
                            ("OTHER", "其他"),
                        ],
                        max_length=10,
                        verbose_name="支付渠道",
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="商家或交易对象"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "手工"),
                            ("IMPORT", "导入"),
                            ("SYSTEM", "系统"),
                        ],
                        default="MANUAL",
                        max_length=10,
                        verbose_name="来源",
                    ),
                ),
                (
                    "is_financial_locked",
                    models.BooleanField(default=False, verbose_name="财务锁定"),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="作废时间"
                    ),
                ),
                (
                    "void_reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="作废或修正原因"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="ledger.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="ledger.merchant",
                        verbose_name="商家",
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_transactions",
                        to="ledger.transaction",
                        verbose_name="关联交易",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ledger.tag"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledger.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                related_name="transactions",
                through="ledger.TransactionTag",
                to="ledger.tag",
            ),
        ),
        migrations.CreateModel(
            name="TransactionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_delta",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="余额变化"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_entries",
                        to="accounts.account",
                        verbose_name="账户",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ledger.transaction",
                        verbose_name="交易",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["account", "transaction"],
                        name="ledger_tran_account_c1acfa_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance_delta", 0), _negated=True),
                        name="ledger_entry_delta_nonzero",
                    ),
                    models.UniqueConstraint(
                        fields=("transaction", "account"),
                        name="ledger_one_entry_per_account",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transactiontag",
            constraint=models.UniqueConstraint(
                fields=("transaction", "tag"), name="ledger_unique_transaction_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "occurred_at"], name="ledger_tran_status_442a01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "occurred_at"],
                name="ledger_tran_transac_0d4338_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "budget_month"],
                name="ledger_tran_categor_f56d7d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ledger_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_month__isnull", True),
                    ("budget_month__day", 1),
                    _connector="OR",
                ),
                name="ledger_budget_month_first_day",
            ),
        ),
    ]
