# Generated by Django 5.2.16 on 2026-07-13 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accountreconciliation"),
        ("ledger", "0004_default_impulse_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("income", "收入"),
                            ("expense", "普通支出"),
                            ("credit-card-expense", "信用卡消费"),
                            ("transfer", "账户转账"),
                            ("credit-card-repayment", "信用卡还款"),
                        ],
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="金额"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("BANK", "银行"),
                            ("WECHAT", "微信"),
                            ("ALIPAY", "支付宝"),
                            ("DIRECT", "直接交易"),
                            ("OTHER", "其他"),
                        ],
                        max_length=10,
                        verbose_name="支付渠道",
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="商家或交易对象"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="显示顺序"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_templates",
                        to="ledger.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "primary_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_transaction_templates",
                        to="accounts.account",
                        verbose_name="主要账户",
                    ),
                ),
                (
                    "secondary_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secondary_transaction_templates",
                        to="accounts.account",
                        verbose_name="目标账户或信用卡",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="ledger_tpl_amount_positive",
                    )
                ],
            },
        ),
    ]
