# Generated by Django 5.2.17 on 2026-08-15 13:08

from django.db import migrations, models


def split_shared_tags(apps, schema_editor):
    tag_model = apps.get_model("ledger", "Tag")
    transaction_tag_model = apps.get_model("ledger", "TransactionTag")

    usage = (
        transaction_tag_model.objects.values(
            "tag_id", "transaction__transaction_type"
        )
        .distinct()
    )
    income_tag_ids = {
        row["tag_id"]
        for row in usage
        if row["transaction__transaction_type"] == "INCOME"
    }
    expense_tag_ids = {
        row["tag_id"]
        for row in usage
        if row["transaction__transaction_type"] == "EXPENSE"
    }

    for tag in tag_model.objects.all():
        used_for_income = tag.id in income_tag_ids
        used_for_expense = tag.id in expense_tag_ids
        if used_for_income and not used_for_expense:
            tag.applies_to = "INCOME"
            tag.save(update_fields=["applies_to"])
        elif used_for_income and used_for_expense:
            income_tag = tag_model.objects.create(
                name=tag.name, applies_to="INCOME", is_active=tag.is_active
            )
            transaction_tag_model.objects.filter(
                tag_id=tag.id, transaction__transaction_type="INCOME"
            ).update(tag_id=income_tag.id)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_transactiontemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['applies_to', 'name', 'id']},
        ),
        migrations.AddField(
            model_name='tag',
            name='applies_to',
            field=models.CharField(choices=[('INCOME', '收入'), ('EXPENSE', '支出')], default='EXPENSE', max_length=10, verbose_name='适用类型'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='标签名称'),
        ),
        migrations.RunPython(split_shared_tags, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('applies_to', 'name'), name='ledger_unique_tag_name_per_type'),
        ),
    ]
