# Generated by Django 5.2.17 on 2026-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_tag_applies_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='transactiontemplate',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目名称'),
        ),
    ]
