# Generated by Django 5.2.16 on 2026-07-13 06:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_accountreconciliation"),
        ("ledger", "0004_default_impulse_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(unique=True, verbose_name="预算月份")),
                (
                    "total_expense_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="月度总支出预算",
                    ),
                ),
                (
                    "savings_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="储蓄目标",
                    ),
                ),
                (
                    "minimum_safety_buffer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="最低安全余量",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-month"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("month__day", 1)),
                        name="budgets_month_first_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_expense_budget__gte", 0)),
                        name="budgets_total_expense_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("savings_target__gte", 0)),
                        name="budgets_savings_target_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minimum_safety_buffer__gte", 0)),
                        name="budgets_safety_buffer_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlannedCashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "direction",
                    models.CharField(
                        choices=[("INCOME", "预计收入"), ("EXPENSE", "固定支出")],
                        max_length=10,
                        verbose_name="方向",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="计划金额",
                    ),
                ),
                (
                    "reliability",
                    models.CharField(
                        choices=[
                            ("CERTAIN", "确定"),
                            ("LIKELY", "较可能"),
                            ("UNCERTAIN", "不确定"),
                        ],
                        default="CERTAIN",
                        max_length=10,
                        verbose_name="可靠程度",
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "一次"),
                            ("MONTHLY", "每月"),
                            ("YEARLY", "每年"),
                        ],
                        max_length=10,
                        verbose_name="发生周期",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="每月日期",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_cash_flows",
                        to="ledger.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "default_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_cash_flows",
                        to="accounts.account",
                        verbose_name="默认账户",
                    ),
                ),
            ],
            options={
                "ordering": ["direction", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlannedCashFlowOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="预计日期")),
                (
                    "planned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="计划金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "待发生"),
                            ("CONFIRMED", "已确认"),
                            ("SKIPPED", "已跳过"),
                            ("EXPIRED", "已过期"),
                        ],
                        default="PLANNED",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_cash_flow_occurrence",
                        to="ledger.transaction",
                        verbose_name="正式交易",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="budgets.plannedcashflow",
                        verbose_name="计划",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReserveMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("CONTRIBUTION", "转入储备"),
                            ("WITHDRAWAL", "动用储备"),
                            ("CORRECTION", "储备修正"),
                        ],
                        max_length=16,
                        verbose_name="变动类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="金额"
                    ),
                ),
                ("occurred_on", models.DateField(verbose_name="发生日期")),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reserve_movements",
                        to="ledger.transaction",
                        verbose_name="关联交易",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CategoryBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="分类预算",
                    ),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="提醒阈值（%）",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_budgets",
                        to="ledger.category",
                    ),
                ),
                (
                    "monthly_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_budgets",
                        to="budgets.monthlybudget",
                    ),
                ),
            ],
            options={
                "ordering": ["category__sort_order", "category_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monthly_budget", "category"),
                        name="budgets_unique_month_category",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("budget_amount__gte", 0)),
                        name="budgets_category_amount_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("warning_threshold__gte", 0),
                            ("warning_threshold__lte", 100),
                        ),
                        name="budgets_warning_threshold_range",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="plannedcashflow",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="budgets_plan_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedcashflow",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 31)),
                name="budgets_plan_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedcashflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="budgets_plan_end_not_before_start",
            ),
        ),
        migrations.AddIndex(
            model_name="plannedcashflowoccurrence",
            index=models.Index(
                fields=["status", "due_date"], name="budgets_pla_status_f71b67_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedcashflowoccurrence",
            constraint=models.UniqueConstraint(
                fields=("plan", "due_date"), name="budgets_unique_plan_due_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedcashflowoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_amount__gt", 0)),
                name="budgets_occurrence_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedcashflowoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_at__isnull", False),
                        ("linked_transaction__isnull", False),
                        ("status", "CONFIRMED"),
                    ),
                    models.Q(
                        models.Q(("status", "CONFIRMED"), _negated=True),
                        ("linked_transaction__isnull", True),
                        ("confirmed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="budgets_occurrence_confirmation_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservemovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("movement_type", "CORRECTION"),
                        models.Q(("amount", 0), _negated=True),
                    ),
                    models.Q(
                        ("movement_type__in", ["CONTRIBUTION", "WITHDRAWAL"]),
                        ("amount__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="budgets_reserve_amount_matches_type",
            ),
        ),
    ]
