# Generated by Django 5.2.17 on 2026-08-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='savings_settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='实际结转储蓄金额'),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='savings_settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='储蓄结转时间'),
        ),
    ]
