# Generated by Django 5.2.17 on 2026-08-16 15:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_account_type_wealth'),
        ('ledger', '0007_transaction_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WealthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('account_type', models.CharField(choices=[('DEPOSIT', '存款'), ('MONEY_FUND', '货币基金'), ('BOND_FUND', '债券基金'), ('INDEX_FUND', '指数基金'), ('OTHER', '其他')], max_length=20, verbose_name='理财类型')),
                ('institution', models.CharField(blank=True, max_length=100, verbose_name='机构')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='当前市值')),
                ('valuation_date', models.DateField(blank=True, null=True, verbose_name='估值日期')),
                ('fund_code', models.CharField(blank=True, max_length=20, verbose_name='基金代码')),
                ('auto_fetch_enabled', models.BooleanField(default=False, verbose_name='自动同步余额宝收益率')),
                ('seven_day_annual_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='七日年化收益率（%）')),
                ('per_ten_thousand_income', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='每万份收益')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('opened_on', models.DateField(blank=True, null=True, verbose_name='开户日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wealth_account', to='accounts.account', verbose_name='关联核心账户')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WealthFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('TRANSFER_IN', '转入理财'), ('TRANSFER_OUT', '转出理财'), ('INCOME', '理财收益'), ('VALUATION', '估值调整')], max_length=20, verbose_name='流水类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('occurred_on', models.DateField(verbose_name='发生日期')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wealth_flows', to='ledger.transaction', verbose_name='关联核心交易')),
                ('wealth_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='wealth.wealthaccount', verbose_name='理财账户')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='wealthaccount',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', 0)), name='wealth_current_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wealthflow',
            constraint=models.CheckConstraint(condition=models.Q(('flow_type', 'VALUATION'), ('amount__gt', 0), _connector='OR'), name='wealth_flow_amount_positive_for_cash_types'),
        ),
    ]
