# Generated by Django 5.2.16 on 2026-07-12 14:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_accountreconciliation"),
        ("ledger", "0004_default_impulse_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="信用额度",
                    ),
                ),
                (
                    "personal_monthly_limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="个人月度消费上限",
                    ),
                ),
                (
                    "statement_day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="账单日",
                    ),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="还款日",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_card_profile",
                        to="accounts.account",
                        verbose_name="账户",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_start", models.DateField(verbose_name="账期开始")),
                ("cycle_end", models.DateField(verbose_name="账期结束")),
                ("due_date", models.DateField(verbose_name="还款日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "未出账"),
                            ("ISSUED", "待还款"),
                            ("PARTIALLY_PAID", "部分还款"),
                            ("PAID", "已全额还款"),
                            ("OVERDUE", "已逾期"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "official_statement_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="正式账单金额",
                    ),
                ),
                (
                    "official_due_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="正式应还金额",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认出账时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit_card_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_cycles",
                        to="credit.creditcardprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-cycle_end", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BillingCycleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CHARGE", "普通消费"),
                            ("INSTALLMENT", "分期"),
                            ("REFUND", "退款"),
                            ("REPAYMENT", "还款"),
                            ("FEE", "手续费"),
                            ("ADJUSTMENT", "调整"),
                        ],
                        max_length=12,
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="分配金额"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=500, verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="credit.billingcycle",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_cycle_items",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("allocated_amount__gt", 0)),
                        name="credit_allocated_amount_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("billing_cycle", "transaction", "item_type"),
                        name="credit_unique_cycle_transaction_type",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("item_type__in", ["CHARGE", "INSTALLMENT"])
                        ),
                        fields=("transaction",),
                        name="credit_charge_assigned_once",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("item_type", "REFUND")),
                        fields=("transaction",),
                        name="credit_refund_assigned_once",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="creditcardprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="credit_one_active_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditcardprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_limit__gte", 0)),
                name="credit_limit_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditcardprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("personal_monthly_limit__gte", 0)),
                name="credit_personal_limit_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="billingcycle",
            index=models.Index(
                fields=["status", "due_date"], name="credit_bill_status_b4991b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingcycle",
            constraint=models.UniqueConstraint(
                fields=("credit_card_profile", "cycle_start", "cycle_end"),
                name="credit_unique_billing_cycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("cycle_start__lte", models.F("cycle_end"))),
                name="credit_cycle_start_lte_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("cycle_end__lt", models.F("due_date"))),
                name="credit_cycle_end_before_due",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("official_statement_amount__isnull", True),
                    ("official_statement_amount__gte", 0),
                    _connector="OR",
                ),
                name="credit_official_statement_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("official_due_amount__isnull", True),
                    ("official_due_amount__gte", 0),
                    _connector="OR",
                ),
                name="credit_official_due_nonnegative",
            ),
        ),
    ]
