# Generated by Django 5.2.16 on 2026-07-13 05:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credit", "0001_initial"),
        ("ledger", "0004_default_impulse_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="商品名称"),
                ),
                ("purchase_date", models.DateField(verbose_name="购买日期")),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="商品原价",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("CREDIT_CARD", "信用卡"), ("PLATFORM", "平台分期")],
                        max_length=16,
                        verbose_name="分期来源",
                    ),
                ),
                (
                    "installment_count",
                    models.PositiveSmallIntegerField(verbose_name="分期期数"),
                ),
                (
                    "default_installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="默认每期金额",
                    ),
                ),
                ("first_due_month", models.DateField(verbose_name="首期月份")),
                (
                    "total_repayment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="总还款金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "进行中"),
                            ("COMPLETED", "已完成"),
                            ("EARLY_SETTLED", "提前结清"),
                            ("CANCELLED", "已取消"),
                            ("REFUND_PROCESSING", "退款处理中"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plans",
                        to="ledger.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InstallmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveSmallIntegerField(verbose_name="期次"),
                ),
                ("due_date", models.DateField(verbose_name="预计到期日")),
                ("due_month", models.DateField(verbose_name="预算月份")),
                (
                    "planned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="计划金额",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="实际金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "待发生"),
                            ("POSTED", "已入账"),
                            ("CANCELLED", "已取消"),
                            ("WAIVED", "已豁免"),
                        ],
                        default="PLANNED",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="入账时间"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_items",
                        to="credit.billingcycle",
                        verbose_name="信用卡账期",
                    ),
                ),
                (
                    "ledger_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_item",
                        to="ledger.transaction",
                        verbose_name="正式交易",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="installments.installmentplan",
                        verbose_name="分期计划",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="InstallmentAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("AMOUNT_CHANGE", "金额变更"),
                            ("CANCEL_REMAINING", "取消剩余期次"),
                            ("REFUND", "退款"),
                            ("EARLY_SETTLEMENT", "提前结清"),
                            ("MANUAL_CORRECTION", "手工修正"),
                        ],
                        max_length=20,
                        verbose_name="调整类型",
                    ),
                ),
                (
                    "amount_delta",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="金额变化"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_adjustments",
                        to="ledger.transaction",
                        verbose_name="关联交易",
                    ),
                ),
                (
                    "installment_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="installments.installmentitem",
                        verbose_name="分期期次",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="installments.installmentplan",
                        verbose_name="分期计划",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_price__gt", 0)),
                name="installments_original_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("installment_count__gt", 0)),
                name="installments_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_installment_amount__gt", 0)),
                name="installments_default_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_repayment_amount__gt", 0)),
                name="installments_total_repayment_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("first_due_month__day", 1)),
                name="installments_first_due_month_first_day",
            ),
        ),
        migrations.AddIndex(
            model_name="installmentitem",
            index=models.Index(
                fields=["status", "due_month"], name="installment_status_80dbcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installmentitem",
            index=models.Index(
                fields=["status", "due_date"], name="installment_status_108486_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "sequence_number"),
                name="installments_unique_plan_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_amount__gt", 0)),
                name="installments_planned_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_amount__isnull", True),
                    ("actual_amount__gt", 0),
                    _connector="OR",
                ),
                name="installments_actual_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_month__day", 1)),
                name="installments_due_month_first_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actual_amount__isnull", False),
                        ("ledger_transaction__isnull", False),
                        ("posted_at__isnull", False),
                        ("status", "POSTED"),
                    ),
                    models.Q(
                        models.Q(("status", "POSTED"), _negated=True),
                        ("actual_amount__isnull", True),
                        ("ledger_transaction__isnull", True),
                        ("billing_cycle__isnull", True),
                        ("posted_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="installments_posted_relationships_consistent",
            ),
        ),
    ]
