# Generated by Django 5.2.16 on 2026-07-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_accountreconciliation"),
        ("ledger", "0004_default_impulse_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "待识别"),
                            ("ALIPAY", "支付宝"),
                            ("WECHAT", "微信"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "已上传"),
                            ("PARSING", "解析中"),
                            ("WAITING_CONFIRMATION", "待确认"),
                            ("PARTIALLY_IMPORTED", "部分导入"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="UPLOADED",
                        max_length=24,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                ("temporary_file_path", models.CharField(blank=True, max_length=1000)),
                ("parser_name", models.CharField(blank=True, max_length=100)),
                ("parser_version", models.CharField(blank=True, max_length=30)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("file_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("ignored_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "WAITING_CONFIRMATION",
                                    "PARTIALLY_IMPORTED",
                                    "COMPLETED",
                                ],
                            )
                        ),
                        fields=("file_sha256",),
                        name="imports_unique_successful_file_hash",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("external_order_id", models.CharField(blank=True, max_length=200)),
                ("source_external_key", models.CharField(blank=True, max_length=320)),
                (
                    "exact_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate_transaction_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "收入"),
                            ("EXPENSE", "支出"),
                            ("REFUND", "退款"),
                            ("TRANSFER", "转账"),
                            ("UNKNOWN", "未知"),
                            ("IGNORE", "忽略"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("counterparty_raw", models.CharField(blank=True, max_length=200)),
                ("payment_method_raw", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待确认"),
                            ("DUPLICATE_SUSPECTED", "疑似重复"),
                            ("READY", "可导入"),
                            ("IMPORTED", "已导入"),
                            ("IGNORED", "已忽略"),
                            ("FAILED", "解析失败"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("review_flags", models.JSONField(blank=True, default=list)),
                ("sanitized_raw_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "imported_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_record",
                        to="ledger.transaction",
                    ),
                ),
                (
                    "mapped_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapped_import_records",
                        to="accounts.account",
                    ),
                ),
                (
                    "selected_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_import_records",
                        to="ledger.category",
                    ),
                ),
                (
                    "suggested_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suggested_import_records",
                        to="ledger.category",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "id"],
                "indexes": [
                    models.Index(
                        fields=["batch", "status"], name="imports_batch_status_idx"
                    ),
                    models.Index(
                        fields=["external_transaction_id"],
                        name="imports_external_id_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"), name="imports_unique_batch_row"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "IMPORTED"),
                            models.Q(("source_external_key", ""), _negated=True),
                        ),
                        fields=("source_external_key",),
                        name="imports_unique_imported_external_key",
                    ),
                ],
            },
        ),
    ]
