# Generated by Django 5.2.16 on 2026-07-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accountreconciliation"),
        ("imports", "0001_initial"),
        ("ledger", "0004_default_impulse_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="importrecord",
            name="duplicate_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KEEP_MANUAL", "保留现有记录"),
                    ("REPLACE_MANUAL", "使用导入记录替换"),
                    ("KEEP_BOTH", "两条都保留"),
                    ("MERGE", "合并信息"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ImportAccountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "待识别"),
                            ("ALIPAY", "支付宝"),
                            ("WECHAT", "微信"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "match_kind",
                    models.CharField(
                        choices=[("EXACT", "精确匹配"), ("CONTAINS", "包含匹配")],
                        max_length=10,
                    ),
                ),
                ("pattern", models.CharField(max_length=200)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_account_rules",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"],
                        name="imports_imp_is_acti_ce4d8e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "match_kind", "pattern"),
                        name="imports_unique_account_rule_pattern",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportDuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_kind",
                    models.CharField(
                        choices=[
                            ("EXACT_EXTERNAL_ID", "外部流水号一致"),
                            ("EXACT_FINGERPRINT", "标准指纹一致"),
                            ("FUZZY", "疑似手工重复"),
                            ("REFUND_CANDIDATE", "退款原交易候选"),
                        ],
                        max_length=24,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidates",
                        to="imports.importrecord",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_candidates",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("import_record", "transaction", "match_kind"),
                        name="imports_unique_duplicate_candidate",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_selected", True)),
                        fields=("import_record",),
                        name="imports_one_selected_candidate",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__lte", 100)),
                        name="imports_candidate_score_lte_100",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MerchantCategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "match_target",
                    models.CharField(
                        choices=[
                            ("MERCHANT", "交易对方"),
                            ("ITEM", "商品名称"),
                            ("BUSINESS_TYPE", "平台业务类型"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "match_kind",
                    models.CharField(
                        choices=[("EXACT", "精确匹配"), ("CONTAINS", "包含匹配")],
                        max_length=10,
                    ),
                ),
                ("pattern", models.CharField(max_length=200)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchant_category_rules",
                        to="ledger.category",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"],
                        name="imports_mer_is_acti_6633ff_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match_target", "match_kind", "pattern"),
                        name="imports_unique_category_rule_pattern",
                    )
                ],
            },
        ),
    ]
